language: r
sudo: false
cache: packages
warnings_are_errors: true
use_bioc: true
bioc_required: true
cran: http://cran.rstudio.com
addons:
  apt:
    packages:
    - libfftw3-dev
    - libgsl0-dev
    - libgsl0ldbl
os:
- linux
- osx
osx_image: xcode9
dist: trusty
env:
  global:
  - RGL_USE_NULL=TRUE
  - PROJECT_NAME=neuroconductor
  - DISPLAY=:99.0
r_check_args: "--as-cran"
before_install:
- export PROJ_DIR=`basename $PWD`
- fname=travis_helpers.sh
- wget -O ${fname} http://bit.ly/travis_helpers
- cat ${fname}; source ${fname}; rm ${fname}
- cat DESCRIPTION
- start_xvfb ;
- no_open_mp ;
- Rscript -e 'source("https://install-github.me/mangothecat/callr")'
- remove_neuroc_packages
- cat DESCRIPTION
- install_remotes_no_dep
- cat DESCRIPTION
- export PACKAGE_NAME=`package_name`
- if [[ "${PACKAGE_NAME}" == "waveslim" ]]; then fftw_install ; fi
- if [[ "${PACKAGE_NAME}" == "dti" ]]; then gsl_install ; fi
after_success:
- cat ${PACKAGE_NAME}.Rcheck/00install.out
- cat ${PACKAGE_NAME}.Rcheck/00check.log
after_failure:
- cat ${PACKAGE_NAME}.Rcheck/00install.out
- cat ${PACKAGE_NAME}.Rcheck/00check.log
before_deploy:
- travis_wait 100 R CMD INSTALL --build ${PKG_TARBALL}
- if [[ "${TRAVIS_OS_NAME}" = "osx" ]]; then rm -f *.tar.gz; fi
deploy:
  provider: releases
  skip_cleanup: true
  file_glob: true
  file: "${PACKAGE_NAME}*.t*gz"
  on:
    tags: true
  api-key:
    secure: E+iGQpxC0dlMIi5VPTY7FvbnLq2F3LenfDHFG48uwXmWHyaMtQASQ1v5gSPDbjFPCCUv6H5HbfXb4yzoriww+U8y9uM5meBKJF2VrDSc1r/VmS9IYkiao/pwtUln+bjo/N6MZdZ9DRrmhppW5Xe9S6E+Xw01jd2IN9H+jPxkXzN5bZF5KU76ie1BEviRf138ppoFnw8AilpiNJELBm2ktrXxP57mSj9wdJQI/c4j8AST55FsMkxgFzEELUOgq94cYF7u+9X7b4q/BJ4kEtg2wWDeHz7s5NvUFqNzkXFwpKjusER6Zu5G0zxBj2azPfAbsr3aj18FwvN7NeItzHjxUSTcpg5HrLRRRpPTrfXTO89M2LA5yvMwVdFA9hT4Bs6XNMdSxT3EtxdjUOVumx9Mz8eGB/2hw9ZrzwDumJ3WlQ9wNk1FyIGbNevqDghojzBRAeBmq+FhzKHAtAYyb+Rby0997sgQqrTLefo0eOQySCF/yJ1Xd1xuWfb092PGZju0ZdEjLDUou9848uk8IyWQtY/PnGwyW62pDpIkJLdjdPSUj1gdkgyzlmF4/tkow3m0QMDuchEOaykDU6SzzzQjLS1o/2W5R1C1l339XAFOWwkU8mvYielQX4ce9RWF21SKWgSnmWzbp51EA+AuMuPzotEwIxrMCmOWBvSKKJgPE0Q=
after_deploy:
- if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then Rscript -e 'covr::coveralls(type =
  "all")' ; fi
