language: r
sudo: false
cache: packages
warnings_are_errors: true
use_bioc: true
bioc_required: true
cran: http://cran.rstudio.com
addons:
  apt:
    packages:
    - libfftw3-dev
    - libgsl0-dev
    - libgsl0ldbl
os:
- linux
- osx
osx_image: xcode9
dist: trusty
env:
  global:
  - RGL_USE_NULL=TRUE
  - PROJECT_NAME=neuroconductor
  - DISPLAY=:99.0
r_check_args: "--as-cran"
before_install:
- export PROJ_DIR=`basename $PWD`
- fname=travis_helpers.sh
- wget -O ${fname} http://bit.ly/travis_helpers
- cat ${fname}; source ${fname}; rm ${fname}
- cat DESCRIPTION
- start_xvfb ;
- no_open_mp ;
- Rscript -e 'source("https://install-github.me/mangothecat/callr")'
- remove_neuroc_packages
- cat DESCRIPTION
- install_remotes_no_dep
- cat DESCRIPTION
- export PACKAGE_NAME=`package_name`
- if [[ "${PACKAGE_NAME}" == "waveslim" ]]; then fftw_install ; fi
- if [[ "${PACKAGE_NAME}" == "dti" ]]; then gsl_install ; fi
after_success:
- cat ${PACKAGE_NAME}.Rcheck/00install.out
- cat ${PACKAGE_NAME}.Rcheck/00check.log
after_failure:
- cat ${PACKAGE_NAME}.Rcheck/00install.out
- cat ${PACKAGE_NAME}.Rcheck/00check.log
before_deploy:
- travis_wait 100 R CMD INSTALL --build ${PKG_TARBALL}
- if [[ "${TRAVIS_OS_NAME}" = "osx" ]]; then rm -f *.tar.gz; fi
deploy:
  provider: releases
  skip_cleanup: true
  file_glob: true
  file: "${PACKAGE_NAME}*.t*gz"
  on:
    tags: true
  api-key:
    secure: NCI1tZiT8eVA8Hzy/e9xREFQk3SUOOrv7wEIBdd0wWeX3dUcgGxnnOxRnBdU1f9Ihw4YKgH2IcSvHzCEaqW99vwZnyg28xnq9rw48ScEA43yxq39IOFucQfo8mg9es4miMMqGzL1wDFq7AL7FI2oQskSRzfGME2tM/OrDlRExQznZXhl8+FKKWHdBb18qmR9oQzj2eZBU0L2LLs1WckoPLEvNFhm68L0essANbQEblVcYjDQwva7TSgSuRReaUMxV2cnXPhnB9Bajk/0e/Xv1xqAIDy8C8zvJZoi9YtD4kLghKPyM00DdeVN5hIhA6N/A5A90/nHwoGptTd42GBc5p+z//sT7TSXLmHyrn+qVJdnTkeHUbGi8ov1Ij4dnI9rmHQg9CW7jCVw1xsm+8lhnnB2x2stR54aJW/ndJ8t9HXFyBPpKB4Rvp78cCCvdQmhOJ+VkPSFFP9GlNhnf7wmq7XJEEhbjAdiVp3Ol4gxo/SDAsCNPpSGWE81b8cGSKf8oij7P5Ycp/o/r1gtqq8CgHZbNMedBln988POcglro3Yhj+n93KZcWfrLtlQDk/uisW/zYU3wfRf1NOi6R2ctHGsjKX8souqaOERjBdyzQRv7F8f+0NzDPGj/q7AhITar0xBHUeqNOVN5s/H40Jz+CQuvgRjAJ8Uy36RFqMbe14g=
after_deploy:
- if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then Rscript -e 'covr::coveralls(type =
  "all")' ; fi
