language: r
sudo: false
cache: packages
warnings_are_errors: true
use_bioc: true
bioc_required: true
cran: http://cran.rstudio.com
os:
- linux
- osx
env:
  global:
  - RGL_USE_NULL=TRUE
  - PROJECT_NAME=neuroconductor
r_check_args: "--as-cran"
before_install:
- export PROJ_DIR=`basename $PWD`
- fname=travis_helpers.sh
- wget -O ${fname} http://bit.ly/travis_helpers
- cat ${fname}; source ${fname}; rm ${fname}
- cat DESCRIPTION
- Rscript -e 'source("https://install-github.me/mangothecat/callr")'
- remove_neuroc_packages
- cat DESCRIPTION
- install_remotes_no_dep
- cat DESCRIPTION
- export PACKAGE_NAME=`package_name`
- if [[ "${PACKAGE_NAME}" == "waveslim" ]]; then fftw_install ; fi
after_success:
- cat ${PACKAGE_NAME}.Rcheck/00install.out
- cat ${PACKAGE_NAME}.Rcheck/00check.log
after_failure:
- cat ${PACKAGE_NAME}.Rcheck/00install.out
- cat ${PACKAGE_NAME}.Rcheck/00check.log
before_deploy:
- travis_wait 100 R CMD INSTALL --build ${PKG_TARBALL}
- if [[ "${TRAVIS_OS_NAME}" = "osx" ]]; then rm -f *.tar.gz; fi
deploy:
  provider: releases
  skip_cleanup: true
  file_glob: true
  file: "${PACKAGE_NAME}*.t*gz"
  on:
    tags: true
  api-key:
    secure: hgBmYz9RL+RwOd3PPEbD3Zd4rh9bZr4bgx/0pRU5+uziYobz6TOdMGTapjztJnJ9eUsA5vOTKQFXklz7d2WbTRllXWYdY3dIly3LipZRpq8pS/gxRwYqjKUudsfeguV7SGDhyEAgZuP8G0IT0ARuYLsB6aOj/VE4o5ti0D2oshTC+rugKqA50GTJ/a0CNXMnxtZZRGo+sLY7Koefl3X910o58xmeeUQpc93jbGfMHY7gueg8nujGP1VGq157N5dOhJFBqqayruIs6Rz5dcAbVvz3n5Ibc63YmtSq4/cIQ2sOEl6lxMkvHe/usc8aAVZ8P6sgK0AX0BiEQKI3GMd3kRgwPNu3oar60mwjA4NW0pBX03C+Sm1yUPptEBQW/PsUPzzW4oEnQtyp6RwKq4d5HZ4dFDDxf12GWGIOuVsXuBuVmG7mzblxIyfDHIixhdseUWPTXJC64aFArc/8gfHQKaQNr6jCLnHSCX47T5qyZroimB7Eb5n6aEqsjZ9gUsFNG33TC8MCaCLreOh+fOTMQZfaaRKwMNTDf7CM31UzH0lDtkbcuSP/3/FlhysWvlFAhdAf3GVgtx0qhcAEXQu8GlxSdl75IzHggtpVJV1buCz07RUnZPktrwsnIge27z/qPeVh2xY6S0b23xqT2cRVUs+82RmXglqNasFBugzH7vo=
after_deploy:
- if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then Rscript -e 'covr::coveralls(type =
  "all")' ; fi
